### ISSUE TITLE
Only Blazor server-side NOT working in preview5

### ISSUE THREAD

**Issue by uwefms** [syncfusion/ej2-aspnet-core-blazor-samples#18]
Hi,
  I tried to create a server-side blazor app according to your instructions in

https://ej2.syncfusion.com/aspnet-core-blazor/documentation/getting-started/vs-blazor-server/

with preview5.

![11-05-_2019_13-42-44](https://user-images.githubusercontent.com/13874580/57569277-dbe4de00-73f2-11e9-9aaf-a2bc5715967b.jpg)

The app compiles, without rendering the control. It just displays a grey line under the welcome message.

![11-05-_2019_13-45-43](https://user-images.githubusercontent.com/13874580/57569295-32521c80-73f3-11e9-9c78-aa5d44168f51.jpg)

Using your instructions for Blazor client and Blazor client-hosted with preview5 everything is working fine.

I have to develop a rather complex schedule module for events an room booking , so debugging is essential for me at this stage of the project.

**Comment by vijays-git** [comment]
Sorry about the delay. We have fixed the issue and it is available in the latest NuGet package 17.1.0.47+. Please try with the latest version and let us know if you have any question.
