### ISSUE TITLE
Demo not properly working

### ISSUE THREAD

**Issue by Olivercomputing** [syncfusion/ej2-aspnet-core-blazor-samples#21]
I cloned this repo without changes and compiled in Visual Studio 2019 (16.1.0 Preview 3.0) and updated to Syncfusion.EJ2.AspNet.Core.RazorComponents v17.1.0.48-beta. There are 25 warnings but no errors, and the demo executes. However, no matter what's selected in the list of controls to demo, the "DataGrid > Default Functionalities" page is always selected.

**Comment by jesusarockias** [comment]
Hi Philip,
 
Sorry for the delayed response.
 
We have checked the reported issue in a Windows machine with the following configuration.
1.	Windows 10
2.	VS2019 16.1.0 Preview 3
3.	ASP.NET Core SDK Preview 5
4.	Syncfusion Razor Component Package 17.1.0.48-beta
 
But, We are not able to reproduce the reported issue in our end. So, please share your machine configuration to help you better. We have also created a video for reference and you can get it from the link below.

Video: http://www.syncfusion.com/downloads/support/directtrac/236857/ze/blazor-samples1917015352.zip

Regards,
Jesus Arockia Sankaran S

**Comment by Olivercomputing** [comment]
Installing ASP.NET Core SDK Preview 5 fixed the problem, thanks. This stuff is really bleeding edge currently, but I'm happy to see more third party Blazor components.
