### ISSUE TITLE
DiagramNodeAnnotations seems not to work

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#23]
I tried to attach DiagramNodeAnnotations to a DiagramNode, which seems  not to work.
I tried the same with a list of DiagramNodeAnnotation Elements which finally works.

```
            return new DiagramNode
            {
                //Annotations = new DiagramNodeAnnotations{...} // does not work
                Annotations = new List<DiagramNodeAnnotation> {...} // works
            };
```

Also the Alignment seems to be buggy. The horizontal and vertical alignment seems to be inverted.
Maybe it is related to this: https://github.com/syncfusion/ej2-aspnet-core-blazor-samples/issues/25

            var style = new NodeAnnotationStyle {Bold = true, FontFamily = "Comic Sans MS", FontSize = 24};

            return new List<DiagramNodeAnnotation>
            {
                new DiagramNodeAnnotation
                {
                    Content = content,

                    Width = width - 6,
                    Height = height - 6,

                    Style = style,

                    HorizontalAlignment = HorizontalAlignment.Left, // is right
                    VerticalAlignment = VerticalAlignment.Top, // is bottom

                    Offset = new NodeAnnotationOffset{X = 0, Y = 0}, 

                    Constraints = AnnotationConstraints.ReadOnly
                }
            };

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

Query | Response
-- | --
I   tried to attach DiagramNodeAnnotations to a DiagramNode, which seems not to   work.   I tried the same with a list of DiagramNodeAnnotation Elements which finally   works.                 return new DiagramNode                 {                     //Annotations = new DiagramNodeAnnotations{...} // does not work                     Annotations = new List<DiagramNodeAnnotation> {...} // works                 }; | annotations   property of the node /connector is a collection type. So, please define   annotations property using the collection of DiagramNodeAnnotation.
Also the Alignment seems to be buggy. The offset value   seems to be internally multiplied, so the text appears outside the node and   the horizontal and vertical alignment seems to be inverted. | By default,   the node annotations is positioned based on its offset property. So,   the horizontal and vertical alignment to annotation is aligned based on   offset property.       Please   refer to the sample and  drafted version of documentation in which we   have explained the annotation  horizontal and vertical alignments in a   detailed manner.       

Drafted   documentation: http://www.syncfusion.com/downloads/support/directtrac/general/ze/Horizontal_and_vertical_alignment-1256336407       

Sample   Link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/NodeAnnotationSample805526865


Regards, 
Ramya T

**Comment by endeffects** [comment]
Thanks alot for clarification.
