### ISSUE TITLE
How to apply the SelectorConstraints?

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#24]
I've found an example on how to do this for asp.net core, but this does not work with blazor.

```
<script>
    $("#diagram").ejDiagram({
        constraints: ej.datavisualization.Diagram.SelectorConstraints.All & ~(ej.datavisualization.Diagram.SelectorConstraints.Rotator | ej.datavisualization.Diagram.SelectorConstraints.Resizer)
    });
</script>
```

**Comment by RamyaThiru** [comment]
Hi @endeffects , 

We can hide the resizer and rotator options of selector using SelectorConstraints. Please refer to the below code example and sample to achieve this.


Code example:

<EjsDiagram id="diagram" ref="diagram" Width="100%" Height="690px">
             @*remove node resizer and rotator*@
            <DiagramSelector Constraints="SelectorConstraints.All &~(SelectorConstraints.ResizeAll | SelectorConstraints.Rotate)">
            </DiagramSelector>
</EjsDiagram>

Sample Link: http://www.syncfusion.com/downloads/support/directtrac/general/ze/DiagramSelectorSample-57166051

Regards,
Ramya T

**Comment by endeffects** [comment]
Thank you for your help :)
