### ISSUE TITLE
Overview Control not working

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#38]
I tried to include the overview control to my diagram today,
but it contains no content. Is this available in the current state of development?

```
<Diagram id="diagram" @ref="Diagram" Nodes="@Nodes" Connectors="@Connectors" Width="100%" Height="100%" />
<ejs-overview id="overview" sourceID="diagram" />
```

**Comment by RamyaThiru** [comment]
Hi @endeffects,

Overview feature is available, and it is working fine. We have provided code example and simple sample to represent the overview in diagram. Please refer to the code example and sample as below.

Code example:
`<EjsOverview Id="overview" SourceID="diagram" />`

Sample: https://www.syncfusion.com/downloads/support/directtrac/240614/ze/overviewsample1749974297
Regards, 
Ramya T

**Comment by endeffects** [comment]
Thanks you, i have no idea why this does not worked the first time i tried this. Sorry.
