### ISSUE TITLE
TreeView events OnNodeSelected OnNodeClicked not working

### ISSUE THREAD

**Issue by tomasoplt** [syncfusion/ej2-aspnet-core-blazor-samples#6]
Events are not fired after node click.

**Comment by Mydeen-SN** [comment]
Hi @tomasoplt ,

We have resolved the issues with events and fix for this will be included in our latest NuGet package  [17.1.0.42.](https://www.nuget.org/packages/Syncfusion.EJ2.AspNet.Core.RazorComponents/17.1.0.42).

Thanks,
Mydeen S N
