### ISSUE TITLE
Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 is not compatible with netcoreapp2.2

### ISSUE THREAD

**Issue by tomasoplt** [syncfusion/ej2-aspnet-core-blazor-samples#7]
With latest Visual Studio 2019 + SDK 3.0.100-preview4-011223  I am receiving error: 
Error: NU1202	Package Microsoft.AspNetCore.Blazor.Cli 0.9.0-preview3-19154-02 is not compatible with netcoreapp2.2

**Comment by ajithr** [comment]
Hi @tomasoplt ,

Thanks for your interest in Syncfusion products.

We have planned to update our Blazor Components to Preview 4 by our next patch release, which will be available by April 30, 2019.

Please let us know if you need any further assistance on this.

Regards,
Ajith R

**Comment by netclectic** [comment]
Any update on the Preview 4 release?
I'm not seeing any activity on here or NuGet.

**Comment by ajithr** [comment]
Hi @netclectic ,

Sorry for the delay. We have published the latest NuGet and updated the latest code snippets in the github repository. Please refer the below link for more details.

https://www.nuget.org/packages/Syncfusion.EJ2.AspNet.Core.RazorComponents/17.1.0.43-beta

Regards,
Ajith R
