### ISSUE TITLE
Please update to Preview 4

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#8]
Could you please update your Blazor Components to Preview 4?

**Comment by essentialjs2** [comment]
Hi @endeffects ,

Thanks for your interest in Syncfusion products.

We have planned to update our Blazor Components to Preview 4 by our next patch release, which will be available by April 30, 2019.

Please let us know if you need any further assistance on this.

Regards,
Ajith R

**Comment by endeffects** [comment]
Thanks for the information.
