### ISSUE TITLE
Typesafe classes for better code behind support

### ISSUE THREAD

**Issue by endeffects** [syncfusion/ej2-aspnet-core-blazor-samples#9]
I've noticed in your documentation that you are using anonym objects for the whole initialization of your components. Is there any reason for it? I'm writting most of my code in the code behind classes and i would prefer a type safe implementation. Will there be any .net classes for such value object in the future?

Sample:

```
@functions{
    EjsDiagram diagram;
    EjsSymbolPalette palettes;

    private static object getFlowShape(string id, string shapeType) {
        return new { id= id, shape = new { type = "Flow", shape = shapeType } };
    }
    private List<object> nodes { get; set; } = new List<object>()
    ...
}
```

**Comment by RamyaThiru** [comment]
Hi, 

We have created a sample in which we have provided type definition for nodes and connectors. We don’t have support to create type definition for complex objects which is listed below. 

Complex objects in the sample: 
nodes 
style = new { fill= "#357BD2", strokeColor= "white" }, 
shape= new { type= "Flow", shape= "Terminator" }, 

Sample: http://www.syncfusion.com/downloads/support/directtrac/general/ze/blazorsample2053397282 
 
Regards, 
Ramya T

**Comment by RamyaThiru** [comment]
Hi @endeffects ,

Requirement : Support to create the type definition for complex objects or properties

We have provided the support to achieve your requirement and it will be available in our SP1 of Volume 1 release on mid of May 2019.

Now, you can now track the status of your request, review the proposed resolution timeline, and contact us for any further inquiries through below link.  
Link: https://www.syncfusion.com/feedback/6148/provide-tag-support-for-complex-properties

Regards,
Ramya T

**Comment by endeffects** [comment]
Nice, thanks for the feedback!
